filter:
    paths: ["src/*"]

build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: phpunit --coverage-clover=coverage-file
                coverage:
                    file: coverage-file
                    format: php-clover
