language: php
dist: trusty
sudo: false

php:
  - 7.2
  - 7.3

install:
  - composer require symfony/flex
  - composer install

jobs:
  include:
    -
      name: Code Standard
      before_install: phpenv config-rm xdebug.ini
      script: vendor/bin/php-cs-fixer fix --config=.php_cs.dist --dry-run

    -
      name: Unit tests
      before_install: phpenv config-rm xdebug.ini
      script: vendor/bin/phpunit

    - stage: Static analysis
      script:
        - sonar-scanner

    -
      stage: Benchmark
      install:
        - phpenv config-add php.ini
        - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - export BENCHMARK_DIR=/tmp/serializers-benchmarking
        - git clone https://github.com/tsantos84/serializers-benchmarking.git ${BENCHMARK_DIR}
        - cd ${BENCHMARK_DIR}
        - rm -rf composer.lock
        - composer config repositories.serializer path ${TRAVIS_BUILD_DIR}
        - cat composer.json
        - composer clear-cache
        - composer install -a --prefer-source --no-progress

      script:
        - php vendor/bin/phpbench run --warmup=1 --report=tsantos --group=serialize --iterations=10
        - php vendor/bin/phpbench run --warmup=1 --report=tsantos --group=deserialize --iterations=10

  allow_failures:
    -   stage: SonarQube Scanner
    -   stage: Benchmark
