language: php
dist: trusty
sudo: false

php:
  - 7.2
  - 7.3

jobs:
  include:
      - stage: Tests
        name: Code Standard
        script: vendor/bin/php-cs-fixer fix --config=.php_cs.dist --dry-run

