language: php
dist: trusty
sudo: false

addons:
  sonarcloud:
    organization: "tsantos84-github"

env:
  - STABILITY="stable"

php:
  - 7.2
  - 7.3
  - 7.3
    env: STABILITY="dev"
  - 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false

install:
  - composer config minimum-stability $STABILITY
  - composer require symfony/flex
  - composer install --prefer-dist --no-progress

script: vendor/bin/phpunit

jobs:
  include:
    -
      name: Code Standard
      script: vendor/bin/php-cs-fixer fix --config=.php_cs.dist --dry-run
      php: 7.3

    -
      stage: Static analysis
      before_script: git fetch --unshallow
      php: 7.3
      script:
        - vendor/bin/phpunit --coverage-clover reports/phpunit.coverage.xml --log-junit reports/phpunit.report.xml
      after_script:
        - sonar-scanner

    -
      stage: Benchmark
      php: 7.3
      before_install:
        - phpenv config-rm xdebug.ini
        - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - composer require symfony/flex
      install:
        - export BENCHMARK_DIR=/tmp/benchmark
        - git clone https://github.com/tsantos84/serializer-benchmark.git ${BENCHMARK_DIR}
        - cd ${BENCHMARK_DIR}
        - composer require tsantos/serializer:4.0-dev --no-update
        - composer install -a --prefer-source --no-progress

      script:
        - php vendor/bin/phpbench run --warmup=1 --report=tsantos --group=serialize --iterations=10
        - php vendor/bin/phpbench run --warmup=1 --report=tsantos --group=deserialize --iterations=10

  allow_failures:
    -   stage: Static analysis
    -   stage: Benchmark
    -   7.4snapshot
    -   STABILITY=dev
