language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1

    - php: 7.1
      env: DEPENDENCIES="symony/yaml:^3.4||^4.0"

    - php: 7.2
  fast_finish: true

before_install:
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer install -a

script:
  - vendor/bin/phpunit
