language: php

sudo: false

env:
    global:
        - PHPUNIT_FLAGS="-v"

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-clover=coverage.clover"
  fast_finish: true

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - composer install -a

script:
  - vendor/bin/php-cs-fix --config=.php_cs.dist --dry-run
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - |
    # Sending code coverage to Scrutinizer
    if [[ $COVERAGE = true ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

after_success:
  - |
    # Setting up Benchmark Tool
    phpenv config-rm xdebug.ini;
    export BENCHMARK_DIR=/tmp/serializers-benchmarking
    git clone https://github.com/tsantos84/serializers-benchmarking.git ${BENCHMARK_DIR}
    cd ${BENCHMARK_DIR}
    rm -rf composer.lock
    composer config repositories.serializer path ${TRAVIS_BUILD_DIR}
    cat composer.json

  - |
    # Installing Benchmark Dependencies
    composer clear-cache
    composer install -a --prefer-source

  - |
    # Performing serialization benchmark
    php vendor/bin/phpbench run --warmup=1 --report=tsantos --group=serialize --iterations=10

  - |
    # Performing deserialization benchmark
    php vendor/bin/phpbench run --warmup=1 --report=tsantos --group=deserialize --iterations=10
