language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: DEPENDENCIES="symfony/yaml:^3.4||^4.0"
    - php: 7.1
      env: DEPENDENCIES="doctrine/annotations:^1.5"
    - php: 7.2
    - php: 7.2
      env: DEPENDENCIES="symfony/yaml:^3.4||^4.0"
    - php: 7.2
      env: DEPENDENCIES="doctrine/annotations:^1.5"
  fast_finish: true

before_install:
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer install -a

script:
  - vendor/bin/phpcs .
  - vendor/bin/phpunit -v

after_success:
  - export BENCHMARK_DIR=/tmp/serializers-benchmarking
  - git clone https://github.com/tsantos84/serializers-benchmarking.git ${BENCHMARK_DIR}
  - composer config repositories.serializer path ${TRAVIS_BUILD_DIR}
  - composer require tsantos/serializer:*@dev --no-update -d ${BENCHMARK_DIR}
  - composer install -a --no-dev -d ${BENCHMARK_DIR}
  - echo "# Serialization operations using 'ACCESSORS' strategy to read and write data"
  - php ${BENCHMARK_DIR}/app serialize -s 100 -b 100
  - php ${BENCHMARK_DIR}/app deserialize -s 100 -b 100
  - echo "# Serialization operations using 'REFLECTION' strategy to read and write data"
  - export SERIALIZER_ACCESSOR_STRATEGY=REFLECTION
  - php ${BENCHMARK_DIR}/app serialize -s 100 -b 100
  - php ${BENCHMARK_DIR}/app deserialize -s 100 -b 100
